### ISSUE TITLE
class-friends-feed-parser-activitypub.php seems to call wp_unschedule_event() with missing arguments?

### ISSUE THREAD

**Issue by alecmuffett** [pfefferle/wordpress-activitypub#240]
I've installed the friends plugin to use alongside ActivityPub; I'm trying to debug why my feeds are not being fetched.

One thing I have noticed is that my logs are accruing messages like:

```
AH01071: Got error '
PHP message: PHP Warning:  Illegal offset type in /big/blog/wp-includes/cron.php on line 509
PHP message: PHP Warning:  Illegal offset type in isset or empty in /big/blog/wp-includes/cron.php on line 510
PHP message: PHP Warning:  Illegal offset type in unset in /big/blog/wp-includes/cron.php on line 511
', referer: https://alecmuffett.com/wp-admin/admin.php?page=add-friend
```

This references the following function with this signature:

```php
function wp_unschedule_event( $timestamp, $hook, $args = array(), $wp_error = false )
```

and the relevant code is: (with line numbers)

```php
        unset( $crons[ $timestamp ][ $hook ][ $key ] ); // 509
        if ( empty( $crons[ $timestamp ][ $hook ] ) ) { // 510
                unset( $crons[ $timestamp ][ $hook ] ); // 511
        } // 512
        if ( empty( $crons[ $timestamp ] ) ) { // 513
```

Since the log does not complain about `$timestamp` invocation on line 513, I presume that the problem is that `$hook` is unset, evidenced by line 511 being mentioned in the log.

A quick check of `wp-content/plugins/activitypub/integration/class-friends-feed-parser-activitypub.php` shows:

```php
                if ( $unfollow_timestamp ) {
                        // If we just unfollowed, we don't want the event to potentially be executed after our follow event.
                        wp_unschedule_event( $unfollow_timestamp, $args ); // *** where is $hook ? ***
                }
```

...without a hook being passed-in as per the signature.

I am not sure whether this is a Friends-Plugin thing, or an ActivityPub thing, but it may be relevant to why my system is not working.  Can you advise?

Wordpress 6.1 and ActivityPub 0.14.2

**Comment by pfefferle** [comment]
ping @akirk

**Comment by alecmuffett** [comment]
@pfefferle oh!  Am I incorrect to assume that `wp-content/plugins/activitypub/...` makes it an issue with activitypub? 

Or is this a collaboration thing?

**Comment by pfefferle** [comment]
It is a collaboration thing :)

**Comment by akirk** [comment]
Sorry about this, fixed in https://github.com/akirk/friends/commit/3fd3b249a5f8090686780984a4e7cf8e4b2b7427

**Comment by pfefferle** [comment]
I will close the issue for now, please re-open if still a problem!
