### ISSUE TITLE
Following Blog Won't "Stick"

### ISSUE THREAD

**Issue by derpypaws** [pfefferle/wordpress-activitypub#88]
Hey there,

I've been trying different solutions to implement federated blogging for a friend's website on and off for over a year now, and while I'm closer than ever, I'm still having trouble. Using the Activitypub Wordpress plugin, I have the user show up on Mastodon, (@roryprice@roryprice.net), but I haven't gotten a follow request to take. I saw this issue on another thread and it eventually fixed itself, but in that case it took hours for a refresh to show that it hand't worked, but in my case a reload will immediately show that the follow wasn't accepted. This has been the case for weeks. I can see the account had picked up a couple of toots from before, but now it doesn't see any new ones. 

Interestingly, the account did reflect a changed profile picture.

**Comment by xuv** [comment]
I believe this is related to this issue that I reported here on Mastodon: https://merveilles.town/web/statuses/104009265689733976

**Comment by elenners** [comment]
I have the same issue. I cannot follow my blog's account, it shows that I submitted a follow request and nothing further. I had the same issue on multiple Masto instances and one Pleroma instance.

**Comment by pfefferle** [comment]
should be fixed with 0.10.1!

**Comment by mediaformat** [comment]
I’m still having this issue.

I attempt to follow ‘@dev@dev-site.mediaformat.org’ but on refresh it becomes a follow request.

Could it be the dash in the URL?

**Comment by pfefferle** [comment]
@mediaformat have you updated tongue latest version? On which platform have you tested it (mastodon, pletome, ...)?

**Comment by xuv** [comment]
So. I’ve tested with 2 WP instances. And strangely, it’s only fixed on one of them. Weirdly, both WP setup are pretty similar. Both hosted on shared hosting at OVH.

1. @xuv@polymorph.cool
Runs on WP 5.4.1 with WP-AP 0.10.1
When trying to follow from Mastodon, it shows "cancel follow request" after a refresh. And the follow request is never accepted.
There is no "followers" listed on the WP admin page Followers (Fediverse)

2. @juego@p.xuv.be
Runs on WP 5.4.1 with WP-AP 0.10.1
Follow request work as expected. 
There are followers listed on the WP admin page Followers (Fediverse)

Not sure what I can do to debug this further. I’ve checked the Apache log but can’t seem to find anything.

**Comment by mediaformat** [comment]
> @mediaformat have you updated to the latest version? On which platform have you tested it (mastodon, pletome, ...)?

WP 5.4.1
wordpress-activitypub 0.10.1

tested on mastodon.social

**Comment by mediaformat** [comment]
Following up from [wordpress.org/support/topic/secure-mode-compatibility/](https://wordpress.org/support/topic/secure-mode-compatibility/)

I've tested on a shared hosting setup, and finding a similar issue: @foo@staging.mediaformat.org

**Comment by hfte** [comment]
When I send a follow request I get the following PHP Warning:
`PHP Warning:  Undefined variable $user_id in wp-content/plugins/activitypub/includes/rest/class-inbox.php on line 111`
My follow request doesn't "stick" as well.
Wordpress 5.8 on php 8.0

**Comment by ssweeny** [comment]
Hi, I'm seeing the same issue trying to follow my WP site from Fosstodon.

The address I'm trying to follow is @ssweeny@ssweeny.net
I'm on Fosstodon which as of this comment is running Mastodon v4.0.2

One interesting finding:
I turned on debugging on my WP site and tried to follow. It looks as if the "acceptance" message from WP has some issue as I get what I'm pretty sure is the response from Fosstodon with this message:

```
HTTP/1.1 401 Unauthorized
Date: Wed, 30 Nov 2022 05:36:22 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Server: Mastodon
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Permissions-Policy: interest-cohort=()
Vary: Accept
Cache-Control: no-cache
Content-Security-Policy: base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://fosstodon.org; img-src '...
X-Request-Id: 93672c69-5b12-420b-8dbd-8f59a5cca188
X-Runtime: 0.407184
Strict-Transport-Security: max-age=63072000; includeSubDomains

```

Perhaps related, I also see in the log these messages:
```
REST request: /activitypub/1.0/blog/followers: [](Header Absent)
REST result: : {"code":"rest_no_route","message":"No route was found matching the URL and request method.","data":{"status":404}}(404) - [](User ID: 0)
```
